site_name: 茕山羊维基
repo_url: https://github.com/nomdn/GoatBook-Source
repo_name: nomdn/GoatBook-Source
nav:
  - 主页: index.md
  - 会议记录: thing/meeting.md
  - 历史:
      - 历史要事: thing/history/lsys.md
      - 野史: thing/history/ys.md
  - 群法案: thing/faan.md
  - 群机构:
    - 茕羊纪律委员会: thing/jljcwyh.md
    - 柠檬都护府: thing/lemonhufu.md
  - 神人志: name/name.md
  - 专有名词解释: name/name_thing.md
  - 判决记录: thing/objection.md
  - 开发者必读: todeveloper.md

theme:
  name: material
  language : zh
  favicon: https://img.wsmdn.dpdns.org/img/goat.jpg
  icon:
    repo: fontawesome/brands/github
  palette:

    # Toggle light mode
    - scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

    # Toggle dark mode
    - scheme: slate
      primary: blue grey
      accent: blue grey
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
plugins:
  - search:
      separator: '[\s\-\.]+'  # 更好地切分中文和符号
      lang: ['zh']
      # 明确指定中文语言
extra_css:
 - extra.css

markdown_extensions:
  - pymdownx.tabbed
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.superfences
  - attr_list
  - admonition











